version: "3.8"
services:
  # client:
  #   container_name: client-cts
  #   build:
  #     context: ./client
  #     dockerfile: docker/Dockerfile
  #   volumes:
  #     - ./client:/var/www/client
  #     - ./server:/var/www/server
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env

  server:
    container_name: server-cts
    build:
      context: ./server
    working_dir: /var/www/server
    volumes:
      - ./server:/var/www/server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres

  pgadmin:
    container_name: pgadmin-cts
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

  postgres:
    container_name: postgres-cts
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
